//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.14 at 12:18:07 PM CDT 
//


package cl.pullman.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * <p>Java class for asientoProcesoVentaWeb complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="asientoProcesoVentaWeb">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Piso1" type="{http://webservices.pullman.cl/}piso1" minOccurs="0"/>
 *         &lt;element name="Piso2" type="{http://webservices.pullman.cl/}piso2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="AsientoProcesoVentaWeb") 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "asientoProcesoVentaWeb", propOrder = {
    "piso1",
    "piso2"
})
public class AsientoProcesoVentaWeb {

    @XmlElement(name = "Piso1")
    protected Piso1 piso1;
    @XmlElement(name = "Piso2")
    protected Piso2 piso2;

    /**
     * Gets the value of the piso1 property.
     * 
     * @return
     *     possible object is
     *     {@link Piso1 }
     *     
     */
    public Piso1 getPiso1() {
        return piso1;
    }

    /**
     * Sets the value of the piso1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Piso1 }
     *     
     */
    public void setPiso1(Piso1 value) {
        this.piso1 = value;
    }

    /**
     * Gets the value of the piso2 property.
     * 
     * @return
     *     possible object is
     *     {@link Piso2 }
     *     
     */
    public Piso2 getPiso2() {
        return piso2;
    }

    /**
     * Sets the value of the piso2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Piso2 }
     *     
     */
    public void setPiso2(Piso2 value) {
        this.piso2 = value;
    }

}
