//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.05 at 03:06:25 PM CST 
//


package cl.pullman.webservices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * <p>Java class for GetBuscaCiudadResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetBuscaCiudadResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CiudadOrigen" type="{http://webservices.pullman.cl/}ciudad" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="GetBuscaCiudadResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBuscaCiudadResponse", propOrder = {
    "ciudadOrigen"
})
public class GetBuscaCiudadResponse {

    @XmlElement(name = "CiudadOrigen")
    protected List<Ciudad> ciudadOrigen;

    /**
     * Gets the value of the ciudadOrigen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ciudadOrigen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCiudadOrigen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ciudad }
     * 
     * 
     */
    public List<Ciudad> getCiudadOrigen() {
        if (ciudadOrigen == null) {
            ciudadOrigen = new ArrayList<Ciudad>();
        }
        return this.ciudadOrigen;
    }

}
