//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.14 at 12:18:07 PM CDT 
//


package cl.pullman.webservices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * <p>Java class for GetDisponibilidadAsientoResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetDisponibilidadAsientoResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarcaAsiento" type="{http://webservices.pullman.cl/}asientoProcesoVentaWeb" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="GetDisponibilidadAsientoResponse") 
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetDisponibilidadAsientoResponse", propOrder = {
    "marcaAsiento"
})
public class GetDisponibilidadAsientoResponse {

    @XmlElement(name = "MarcaAsiento")
    protected List<AsientoProcesoVentaWeb> marcaAsiento;

    /**
     * Gets the value of the marcaAsiento property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marcaAsiento property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarcaAsiento().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AsientoProcesoVentaWeb }
     * 
     * 
     */
    public List<AsientoProcesoVentaWeb> getMarcaAsiento() {
        if (marcaAsiento == null) {
            marcaAsiento = new ArrayList<AsientoProcesoVentaWeb>();
        }
        return this.marcaAsiento;
    }

}
