//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 12:47:02 PM CDT 
//


package cl.pullman.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * <p>Java class for GetStartSession complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetStartSession">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodigoComercio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PuntoComercio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="GetStartSession")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetStartSession", propOrder = {
    "codigoComercio",
    "puntoComercio"
})
public class GetStartSession {

    @XmlElement(name = "CodigoComercio")
    protected String codigoComercio;
    @XmlElement(name = "PuntoComercio")
    protected String puntoComercio;

    /**
     * Gets the value of the codigoComercio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoComercio() {
        return codigoComercio;
    }

    /**
     * Sets the value of the codigoComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoComercio(String value) {
        this.codigoComercio = value;
    }

    /**
     * Gets the value of the puntoComercio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPuntoComercio() {
        return puntoComercio;
    }

    /**
     * Sets the value of the puntoComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPuntoComercio(String value) {
        this.puntoComercio = value;
    }

}
