//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.29 at 02:50:53 PM CDT 
//


package cl.pullman.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * <p>Java class for GetTarifaServicio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetTarifaServicio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodigoComercio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PuntoComercio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IdSession" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PtoVta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IdServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodigoTerminalOrigen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodigoTerminalDestino" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FechaSalida" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HoraSalida" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClasePiso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumeroBus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Empresa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="GetTarifaServicio")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetTarifaServicio", propOrder = {
    "codigoComercio",
    "puntoComercio",
    "idSession",
    "ptoVta",
    "idServicio",
    "codigoTerminalOrigen",
    "codigoTerminalDestino",
    "fechaSalida",
    "horaSalida",
    "clasePiso",
    "numeroBus",
    "empresa"
})
public class GetTarifaServicio {

    @XmlElement(name = "CodigoComercio")
    protected String codigoComercio;
    @XmlElement(name = "PuntoComercio")
    protected String puntoComercio;
    @XmlElement(name = "IdSession")
    protected String idSession;
    @XmlElement(name = "PtoVta")
    protected String ptoVta;
    @XmlElement(name = "IdServicio")
    protected String idServicio;
    @XmlElement(name = "CodigoTerminalOrigen")
    protected String codigoTerminalOrigen;
    @XmlElement(name = "CodigoTerminalDestino")
    protected String codigoTerminalDestino;
    @XmlElement(name = "FechaSalida")
    protected String fechaSalida;
    @XmlElement(name = "HoraSalida")
    protected String horaSalida;
    @XmlElement(name = "ClasePiso")
    protected String clasePiso;
    @XmlElement(name = "NumeroBus")
    protected String numeroBus;
    @XmlElement(name = "Empresa")
    protected String empresa;

    /**
     * Gets the value of the codigoComercio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoComercio() {
        return codigoComercio;
    }

    /**
     * Sets the value of the codigoComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoComercio(String value) {
        this.codigoComercio = value;
    }

    /**
     * Gets the value of the puntoComercio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPuntoComercio() {
        return puntoComercio;
    }

    /**
     * Sets the value of the puntoComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPuntoComercio(String value) {
        this.puntoComercio = value;
    }

    /**
     * Gets the value of the idSession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSession() {
        return idSession;
    }

    /**
     * Sets the value of the idSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSession(String value) {
        this.idSession = value;
    }

    /**
     * Gets the value of the ptoVta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtoVta() {
        return ptoVta;
    }

    /**
     * Sets the value of the ptoVta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtoVta(String value) {
        this.ptoVta = value;
    }

    /**
     * Gets the value of the idServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdServicio() {
        return idServicio;
    }

    /**
     * Sets the value of the idServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdServicio(String value) {
        this.idServicio = value;
    }

    /**
     * Gets the value of the codigoTerminalOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoTerminalOrigen() {
        return codigoTerminalOrigen;
    }

    /**
     * Sets the value of the codigoTerminalOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoTerminalOrigen(String value) {
        this.codigoTerminalOrigen = value;
    }

    /**
     * Gets the value of the codigoTerminalDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoTerminalDestino() {
        return codigoTerminalDestino;
    }

    /**
     * Sets the value of the codigoTerminalDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoTerminalDestino(String value) {
        this.codigoTerminalDestino = value;
    }

    /**
     * Gets the value of the fechaSalida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaSalida() {
        return fechaSalida;
    }

    /**
     * Sets the value of the fechaSalida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaSalida(String value) {
        this.fechaSalida = value;
    }

    /**
     * Gets the value of the horaSalida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoraSalida() {
        return horaSalida;
    }

    /**
     * Sets the value of the horaSalida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoraSalida(String value) {
        this.horaSalida = value;
    }

    /**
     * Gets the value of the clasePiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClasePiso() {
        return clasePiso;
    }

    /**
     * Sets the value of the clasePiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClasePiso(String value) {
        this.clasePiso = value;
    }

    /**
     * Gets the value of the numeroBus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroBus() {
        return numeroBus;
    }

    /**
     * Sets the value of the numeroBus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroBus(String value) {
        this.numeroBus = value;
    }

    /**
     * Gets the value of the empresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpresa() {
        return empresa;
    }

    /**
     * Sets the value of the empresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpresa(String value) {
        this.empresa = value;
    }

}
