//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.14 at 12:18:07 PM CDT 
//


package cl.pullman.webservices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.pullman.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Piso2_QNAME = new QName("http://webservices.pullman.cl/", "piso2");
    private final static QName _Piso1_QNAME = new QName("http://webservices.pullman.cl/", "piso1");
    private final static QName _Error_QNAME = new QName("http://webservices.pullman.cl/", "Error");
    private final static QName _GetDisponibilidadAsiento_QNAME = new QName("http://webservices.pullman.cl/", "GetDisponibilidadAsiento");
    private final static QName _GetDisponibilidadAsientoResponse_QNAME = new QName("http://webservices.pullman.cl/", "GetDisponibilidadAsientoResponse");
    private final static QName _AsientoDisponible_QNAME = new QName("http://webservices.pullman.cl/", "AsientoDisponible");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.pullman.webservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDisponibilidadAsiento }
     * 
     */
    public GetDisponibilidadAsiento createGetDisponibilidadAsiento() {
        return new GetDisponibilidadAsiento();
    }

    /**
     * Create an instance of {@link GetDisponibilidadAsientoResponse }
     * 
     */
    public GetDisponibilidadAsientoResponse createGetDisponibilidadAsientoResponse() {
        return new GetDisponibilidadAsientoResponse();
    }

    /**
     * Create an instance of {@link AsientoProcesoVentaWeb }
     * 
     */
    public AsientoProcesoVentaWeb createAsientoProcesoVentaWeb() {
        return new AsientoProcesoVentaWeb();
    }

    /**
     * Create an instance of {@link Piso2 }
     * 
     */
    public Piso2 createPiso2() {
        return new Piso2();
    }

    /**
     * Create an instance of {@link Piso1 }
     * 
     */
    public Piso1 createPiso1() {
        return new Piso1();
    }

    /**
     * Create an instance of {@link ServiceFault }
     * 
     */
    public ServiceFault createServiceFault() {
        return new ServiceFault();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Piso2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.pullman.cl/", name = "piso2")
    public JAXBElement<Piso2> createPiso2(Piso2 value) {
        return new JAXBElement<Piso2>(_Piso2_QNAME, Piso2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Piso1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.pullman.cl/", name = "piso1")
    public JAXBElement<Piso1> createPiso1(Piso1 value) {
        return new JAXBElement<Piso1>(_Piso1_QNAME, Piso1 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.pullman.cl/", name = "Error")
    public JAXBElement<ServiceFault> createError(ServiceFault value) {
        return new JAXBElement<ServiceFault>(_Error_QNAME, ServiceFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDisponibilidadAsiento }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.pullman.cl/", name = "GetDisponibilidadAsiento")
    public JAXBElement<GetDisponibilidadAsiento> createGetDisponibilidadAsiento(GetDisponibilidadAsiento value) {
        return new JAXBElement<GetDisponibilidadAsiento>(_GetDisponibilidadAsiento_QNAME, GetDisponibilidadAsiento.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDisponibilidadAsientoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.pullman.cl/", name = "GetDisponibilidadAsientoResponse")
    public JAXBElement<GetDisponibilidadAsientoResponse> createGetDisponibilidadAsientoResponse(GetDisponibilidadAsientoResponse value) {
        return new JAXBElement<GetDisponibilidadAsientoResponse>(_GetDisponibilidadAsientoResponse_QNAME, GetDisponibilidadAsientoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AsientoProcesoVentaWeb }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.pullman.cl/", name = "AsientoDisponible")
    public JAXBElement<AsientoProcesoVentaWeb> createAsientoDisponible(AsientoProcesoVentaWeb value) {
        return new JAXBElement<AsientoProcesoVentaWeb>(_AsientoDisponible_QNAME, AsientoProcesoVentaWeb.class, null, value);
    }

}
