//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.31 at 04:40:06 PM CDT 
//


package cl.pullman.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * <p>Java class for planillaWeb complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="planillaWeb">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Bus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Piso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaseServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NombreClase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Asiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlanillaBus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="PlanillaWeb")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "planillaWeb", propOrder = {
    "bus",
    "piso",
    "claseServicio",
    "nombreClase",
    "asiento",
    "planillaBus"
})
public class PlanillaWeb {

    @XmlElement(name = "Bus")
    protected String bus;
    @XmlElement(name = "Piso")
    protected String piso;
    @XmlElement(name = "ClaseServicio")
    protected String claseServicio;
    @XmlElement(name = "NombreClase")
    protected String nombreClase;
    @XmlElement(name = "Asiento")
    protected String asiento;
    @XmlElement(name = "PlanillaBus")
    protected String planillaBus;

    /**
     * Gets the value of the bus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBus() {
        return bus;
    }

    /**
     * Sets the value of the bus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBus(String value) {
        this.bus = value;
    }

    /**
     * Gets the value of the piso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiso() {
        return piso;
    }

    /**
     * Sets the value of the piso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiso(String value) {
        this.piso = value;
    }

    /**
     * Gets the value of the claseServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaseServicio() {
        return claseServicio;
    }

    /**
     * Sets the value of the claseServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaseServicio(String value) {
        this.claseServicio = value;
    }

    /**
     * Gets the value of the nombreClase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreClase() {
        return nombreClase;
    }

    /**
     * Sets the value of the nombreClase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreClase(String value) {
        this.nombreClase = value;
    }

    /**
     * Gets the value of the asiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsiento() {
        return asiento;
    }

    /**
     * Sets the value of the asiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsiento(String value) {
        this.asiento = value;
    }

    /**
     * Gets the value of the planillaBus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanillaBus() {
        return planillaBus;
    }

    /**
     * Sets the value of the planillaBus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanillaBus(String value) {
        this.planillaBus = value;
    }

}
