//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 05:18:24 PM CST 
//


package cl.pullman.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salidaServicio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salidaServicio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodigoOrigenServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NombreOrigenServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodigoDestinoServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NombreDestinoServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodigoOrigenTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NombreTerminalOrigen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodigoDestinoTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NombreTerminalDestino" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FechaSalida" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HoraSalida" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FechaLlegada" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HoraLlegada" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumeroBus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TipoServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Piso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClasePiso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodigoEmpresa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Prioridad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tarifa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salidaServicio", propOrder = {
    "idServicio",
    "codigoOrigenServicio",
    "nombreOrigenServicio",
    "codigoDestinoServicio",
    "nombreDestinoServicio",
    "codigoOrigenTerminal",
    "nombreTerminalOrigen",
    "codigoDestinoTerminal",
    "nombreTerminalDestino",
    "fechaSalida",
    "horaSalida",
    "fechaLlegada",
    "horaLlegada",
    "numeroBus",
    "tipoServicio",
    "piso",
    "clasePiso",
    "codigoEmpresa",
    "prioridad",
    "tarifa"
})
public class SalidaServicio {

    @XmlElement(name = "IdServicio")
    protected String idServicio;
    @XmlElement(name = "CodigoOrigenServicio")
    protected String codigoOrigenServicio;
    @XmlElement(name = "NombreOrigenServicio")
    protected String nombreOrigenServicio;
    @XmlElement(name = "CodigoDestinoServicio")
    protected String codigoDestinoServicio;
    @XmlElement(name = "NombreDestinoServicio")
    protected String nombreDestinoServicio;
    @XmlElement(name = "CodigoOrigenTerminal")
    protected String codigoOrigenTerminal;
    @XmlElement(name = "NombreTerminalOrigen")
    protected String nombreTerminalOrigen;
    @XmlElement(name = "CodigoDestinoTerminal")
    protected String codigoDestinoTerminal;
    @XmlElement(name = "NombreTerminalDestino")
    protected String nombreTerminalDestino;
    @XmlElement(name = "FechaSalida")
    protected String fechaSalida;
    @XmlElement(name = "HoraSalida")
    protected String horaSalida;
    @XmlElement(name = "FechaLlegada")
    protected String fechaLlegada;
    @XmlElement(name = "HoraLlegada")
    protected String horaLlegada;
    @XmlElement(name = "NumeroBus")
    protected String numeroBus;
    @XmlElement(name = "TipoServicio")
    protected String tipoServicio;
    @XmlElement(name = "Piso")
    protected String piso;
    @XmlElement(name = "ClasePiso")
    protected String clasePiso;
    @XmlElement(name = "CodigoEmpresa")
    protected String codigoEmpresa;
    @XmlElement(name = "Prioridad")
    protected String prioridad;
    @XmlElement(name = "Tarifa")
    protected String tarifa;

    /**
     * Gets the value of the idServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdServicio() {
        return idServicio;
    }

    /**
     * Sets the value of the idServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdServicio(String value) {
        this.idServicio = value;
    }

    /**
     * Gets the value of the codigoOrigenServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoOrigenServicio() {
        return codigoOrigenServicio;
    }

    /**
     * Sets the value of the codigoOrigenServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoOrigenServicio(String value) {
        this.codigoOrigenServicio = value;
    }

    /**
     * Gets the value of the nombreOrigenServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreOrigenServicio() {
        return nombreOrigenServicio;
    }

    /**
     * Sets the value of the nombreOrigenServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreOrigenServicio(String value) {
        this.nombreOrigenServicio = value;
    }

    /**
     * Gets the value of the codigoDestinoServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoDestinoServicio() {
        return codigoDestinoServicio;
    }

    /**
     * Sets the value of the codigoDestinoServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoDestinoServicio(String value) {
        this.codigoDestinoServicio = value;
    }

    /**
     * Gets the value of the nombreDestinoServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreDestinoServicio() {
        return nombreDestinoServicio;
    }

    /**
     * Sets the value of the nombreDestinoServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreDestinoServicio(String value) {
        this.nombreDestinoServicio = value;
    }

    /**
     * Gets the value of the codigoOrigenTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoOrigenTerminal() {
        return codigoOrigenTerminal;
    }

    /**
     * Sets the value of the codigoOrigenTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoOrigenTerminal(String value) {
        this.codigoOrigenTerminal = value;
    }

    /**
     * Gets the value of the nombreTerminalOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreTerminalOrigen() {
        return nombreTerminalOrigen;
    }

    /**
     * Sets the value of the nombreTerminalOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreTerminalOrigen(String value) {
        this.nombreTerminalOrigen = value;
    }

    /**
     * Gets the value of the codigoDestinoTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoDestinoTerminal() {
        return codigoDestinoTerminal;
    }

    /**
     * Sets the value of the codigoDestinoTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoDestinoTerminal(String value) {
        this.codigoDestinoTerminal = value;
    }

    /**
     * Gets the value of the nombreTerminalDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreTerminalDestino() {
        return nombreTerminalDestino;
    }

    /**
     * Sets the value of the nombreTerminalDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreTerminalDestino(String value) {
        this.nombreTerminalDestino = value;
    }

    /**
     * Gets the value of the fechaSalida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaSalida() {
        return fechaSalida;
    }

    /**
     * Sets the value of the fechaSalida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaSalida(String value) {
        this.fechaSalida = value;
    }

    /**
     * Gets the value of the horaSalida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoraSalida() {
        return horaSalida;
    }

    /**
     * Sets the value of the horaSalida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoraSalida(String value) {
        this.horaSalida = value;
    }

    /**
     * Gets the value of the fechaLlegada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaLlegada() {
        return fechaLlegada;
    }

    /**
     * Sets the value of the fechaLlegada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaLlegada(String value) {
        this.fechaLlegada = value;
    }

    /**
     * Gets the value of the horaLlegada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoraLlegada() {
        return horaLlegada;
    }

    /**
     * Sets the value of the horaLlegada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoraLlegada(String value) {
        this.horaLlegada = value;
    }

    /**
     * Gets the value of the numeroBus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroBus() {
        return numeroBus;
    }

    /**
     * Sets the value of the numeroBus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroBus(String value) {
        this.numeroBus = value;
    }

    /**
     * Gets the value of the tipoServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio() {
        return tipoServicio;
    }

    /**
     * Sets the value of the tipoServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio(String value) {
        this.tipoServicio = value;
    }

    /**
     * Gets the value of the piso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPiso() {
        return piso;
    }

    /**
     * Sets the value of the piso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPiso(String value) {
        this.piso = value;
    }

    /**
     * Gets the value of the clasePiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClasePiso() {
        return clasePiso;
    }

    /**
     * Sets the value of the clasePiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClasePiso(String value) {
        this.clasePiso = value;
    }

    /**
     * Gets the value of the codigoEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoEmpresa() {
        return codigoEmpresa;
    }

    /**
     * Sets the value of the codigoEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoEmpresa(String value) {
        this.codigoEmpresa = value;
    }

    /**
     * Gets the value of the prioridad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrioridad() {
        return prioridad;
    }

    /**
     * Sets the value of the prioridad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrioridad(String value) {
        this.prioridad = value;
    }

    /**
     * Gets the value of the tarifa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarifa() {
        return tarifa;
    }

    /**
     * Sets the value of the tarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarifa(String value) {
        this.tarifa = value;
    }

}
