//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.29 at 02:50:53 PM CDT 
//


package cl.pullman.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tarifaServicio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tarifaServicio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PuntoVenta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaseServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodigoTerminalOrigen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CodigoTerminalDestino" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FechaInicioTarifaServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FechaTerminoTarifaServicio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tarifa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TipoTarifa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TermporadaTarifa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UsuarioTarifador" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tarifaServicio", propOrder = {
    "puntoVenta",
    "claseServicio",
    "codigoTerminalOrigen",
    "codigoTerminalDestino",
    "fechaInicioTarifaServicio",
    "fechaTerminoTarifaServicio",
    "tarifa",
    "tipoTarifa",
    "termporadaTarifa",
    "usuarioTarifador"
})
public class TarifaServicio {

    @XmlElement(name = "PuntoVenta")
    protected String puntoVenta;
    @XmlElement(name = "ClaseServicio")
    protected String claseServicio;
    @XmlElement(name = "CodigoTerminalOrigen")
    protected String codigoTerminalOrigen;
    @XmlElement(name = "CodigoTerminalDestino")
    protected String codigoTerminalDestino;
    @XmlElement(name = "FechaInicioTarifaServicio")
    protected String fechaInicioTarifaServicio;
    @XmlElement(name = "FechaTerminoTarifaServicio")
    protected String fechaTerminoTarifaServicio;
    @XmlElement(name = "Tarifa")
    protected String tarifa;
    @XmlElement(name = "TipoTarifa")
    protected String tipoTarifa;
    @XmlElement(name = "TermporadaTarifa")
    protected String termporadaTarifa;
    @XmlElement(name = "UsuarioTarifador")
    protected String usuarioTarifador;

    /**
     * Gets the value of the puntoVenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPuntoVenta() {
        return puntoVenta;
    }

    /**
     * Sets the value of the puntoVenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPuntoVenta(String value) {
        this.puntoVenta = value;
    }

    /**
     * Gets the value of the claseServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaseServicio() {
        return claseServicio;
    }

    /**
     * Sets the value of the claseServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaseServicio(String value) {
        this.claseServicio = value;
    }

    /**
     * Gets the value of the codigoTerminalOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoTerminalOrigen() {
        return codigoTerminalOrigen;
    }

    /**
     * Sets the value of the codigoTerminalOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoTerminalOrigen(String value) {
        this.codigoTerminalOrigen = value;
    }

    /**
     * Gets the value of the codigoTerminalDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoTerminalDestino() {
        return codigoTerminalDestino;
    }

    /**
     * Sets the value of the codigoTerminalDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoTerminalDestino(String value) {
        this.codigoTerminalDestino = value;
    }

    /**
     * Gets the value of the fechaInicioTarifaServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaInicioTarifaServicio() {
        return fechaInicioTarifaServicio;
    }

    /**
     * Sets the value of the fechaInicioTarifaServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaInicioTarifaServicio(String value) {
        this.fechaInicioTarifaServicio = value;
    }

    /**
     * Gets the value of the fechaTerminoTarifaServicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaTerminoTarifaServicio() {
        return fechaTerminoTarifaServicio;
    }

    /**
     * Sets the value of the fechaTerminoTarifaServicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaTerminoTarifaServicio(String value) {
        this.fechaTerminoTarifaServicio = value;
    }

    /**
     * Gets the value of the tarifa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarifa() {
        return tarifa;
    }

    /**
     * Sets the value of the tarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarifa(String value) {
        this.tarifa = value;
    }

    /**
     * Gets the value of the tipoTarifa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoTarifa() {
        return tipoTarifa;
    }

    /**
     * Sets the value of the tipoTarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoTarifa(String value) {
        this.tipoTarifa = value;
    }

    /**
     * Gets the value of the termporadaTarifa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermporadaTarifa() {
        return termporadaTarifa;
    }

    /**
     * Sets the value of the termporadaTarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermporadaTarifa(String value) {
        this.termporadaTarifa = value;
    }

    /**
     * Gets the value of the usuarioTarifador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuarioTarifador() {
        return usuarioTarifador;
    }

    /**
     * Sets the value of the usuarioTarifador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuarioTarifador(String value) {
        this.usuarioTarifador = value;
    }

}
